# name: cellesce
channels:
  - bioconda
  - conda-forge
dependencies:
- python
- pandas
- snakemake
- ipython
- scikit-learn
- matplotlib
- cellprofiler
- seaborn
- pip
# - pip:
  # - -e "../../."
- pip:
  - -e .